name: Build

on:
  push:
    branches-ignore:
      - 'gh-pages'
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build # Have to run processing first so the list.json exists to be included in the the deploy
        run: |
          yarn install --frozen-lockfile --cwd processing 
          yarn install --frozen-lockfile --cwd site
          ./build_all_branches.sh

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: public
          
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
